/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.util.LinkedList;
import java.util.Scanner;
import javax.swing.JOptionPane;

public class Interfaz extends javax.swing.JFrame {

    private Nodo head, tail;
    Scanner leer = new Scanner(System.in);
    LinkedList datos = new LinkedList();

    public Interfaz() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.head = null;
        this.tail = null;
    }

    public void addInicio(Nodo nuevo) {         
        if (listaVacia()) {
            head = tail = nuevo;
        } else {
            nuevo.sig = head;
            head = nuevo;
        }
    }

    public void addFinal(Nodo nuevo) {          
        if (listaVacia()) {
            head = tail = nuevo;
        } else {
            tail.sig = nuevo;
            tail = nuevo;
        }
    }

    public void Insertar(int v) {
        Nodo nuevo = new Nodo(v);
        if (listaVacia()) {
            addInicio(nuevo);
        } else {
            if (head == tail) {
                if (nuevo.valor < head.valor) {
                    head = nuevo;
                    nuevo.sig = tail;
                } else {
                    tail = nuevo;
                    head.sig = nuevo;
                }
            } else {
                Nodo aux = head;
                if (nuevo.valor < aux.valor) {
                    addInicio(nuevo);
                } else {
                    while (aux.sig != null) {
                        if (nuevo.valor > aux.sig.valor) {
                            aux = aux.sig;
                        } else {
                            nuevo.sig = aux.sig;
                            aux.sig = nuevo;
                            break;
                        }
                    }
                }
                if (aux.sig == null) {
                    addFinal(nuevo);
                }
            }
        }
    }

    public boolean listaVacia() {
        if (head == null) {
            return true;
        } else {
            return false;
        }
    }

    public void Recorrer() {
        try {
            Nodo recorrer = head;
            while (recorrer != null) {
                int aux = recorrer.valor;
                String f = Integer.toString(aux);
                Presentar.setText(f);
                recorrer = recorrer.sig;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No hay máa datos");
        }
    }

    public void Ingresar_Datos(int x) {
        datos.offer(x);
    }

    public LinkedList Retornar_Dato() {
        return datos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSalir = new javax.swing.JButton();
        jLabelIcono = new javax.swing.JLabel();
        jButtonInsertar = new javax.swing.JButton();
        jTextFieldMenu = new javax.swing.JTextField();
        Insertar = new javax.swing.JTextField();
        Presentar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtsiguiente = new javax.swing.JTextArea();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonSalir.setBackground(new java.awt.Color(255, 51, 0));
        jButtonSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, -1, -1));

        jLabelIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Icono.png"))); // NOI18N
        jLabelIcono.setText("jLabel1");
        getContentPane().add(jLabelIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 250, 240));

        jButtonInsertar.setText("1. Insertar elemento");
        jButtonInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, -1, -1));

        jTextFieldMenu.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jTextFieldMenu.setForeground(new java.awt.Color(255, 153, 0));
        jTextFieldMenu.setText("MENÚ");
        jTextFieldMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMenuActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 90, -1));

        Insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertarActionPerformed(evt);
            }
        });
        getContentPane().add(Insertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 50, -1));

        Presentar.setText("Presentar");
        Presentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PresentarActionPerformed(evt);
            }
        });
        getContentPane().add(Presentar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, -1, -1));

        txtsiguiente.setColumns(20);
        txtsiguiente.setRows(5);
        jScrollPane1.setViewportView(txtsiguiente);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, -1, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/original.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertarActionPerformed
        Ingresar_Datos(Integer.parseInt(Insertar.getText().toString()));
        Insertar.setText("");
    }//GEN-LAST:event_jButtonInsertarActionPerformed

    private void InsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertarActionPerformed

    }//GEN-LAST:event_InsertarActionPerformed

    private void PresentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PresentarActionPerformed
        try {
            txtsiguiente.setText("");
            txtsiguiente.append("Datos ingresados: " + Retornar_Dato());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No hay más datos");
        }
    }//GEN-LAST:event_PresentarActionPerformed

    private void jTextFieldMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField Insertar;
    private javax.swing.JButton Presentar;
    private javax.swing.JButton jButtonInsertar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelIcono;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldMenu;
    private javax.swing.JTextArea txtsiguiente;
    // End of variables declaration//GEN-END:variables
}
